site_name: MySQL Controller
theme:
  name: material
  palette:
    primary: cyan
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/nakamasato/mysql-operator
extra:
  analytics:
    provider: google
    property: G-9NTB93RVPJ
markdown_extensions:
  - pymdownx.superfences
