apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqldbs.mysql.nakamasato.com
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  group: mysql.nakamasato.com
  names:
    kind: MySQLDB
    listKind: MySQLDBList
    plural: mysqldbs
    singular: mysqldb
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The phase of MySQLDB
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: The reason for the current phase of this MySQLDB
      jsonPath: .status.reason
      name: Reason
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MySQLDB is the Schema for the mysqldbs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MySQLDBSpec defines the desired state of MySQLDB
            properties:
              dbName:
                description: MySQL Database name
                type: string
              mysqlName:
                description: MySQL name
                type: string
            required:
            - dbName
            - mysqlName
            type: object
          status:
            description: MySQLDBStatus defines the observed state of MySQLDB
            properties:
              phase:
                description: The phase of database creation
                type: string
              reason:
                description: The reason for the current phase
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
