
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: mysqls.mysql.nakamasato.com
spec:
  group: mysql.nakamasato.com
  names:
    kind: MySQL
    listKind: MySQLList
    plural: mysqls
    singular: mysql
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.host
      name: Host
      type: string
    - jsonPath: .spec.admin_user
      name: AdminUser
      type: string
    - description: The number of MySQLUsers that belongs to the MySQL
      jsonPath: .status.userCount
      name: UserCount
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MySQL is the Schema for the mysqls API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MySQLSpec defines the desired state of MySQL
            properties:
              admin_password:
                description: AdminPassword is MySQL password to connect target MySQL
                  cluster.
                type: string
              admin_user:
                description: AdminUser is MySQL user to connect target MySQL cluster.
                type: string
              gcp_secret_name:
                description: Secret name for admin password in GCP Secret Manager.
                type: string
              host:
                description: Host is MySQL host of target MySQL cluster.
                type: string
              port:
                default: 3306
                description: Port is MySQL port of target MySQL cluster.
                type: integer
            required:
            - admin_user
            type: object
          status:
            description: MySQLStatus defines the observed state of MySQL
            properties:
              dbCount:
                default: 0
                description: The number of database in this MySQL
                format: int32
                type: integer
              userCount:
                default: 0
                description: The number of users in this MySQL
                format: int32
                type: integer
            required:
            - dbCount
            - userCount
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
