---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: mysqldbs.mysql.nakamasato.com
spec:
  group: mysql.nakamasato.com
  names:
    kind: MySQLDB
    listKind: MySQLDBList
    plural: mysqldbs
    singular: mysqldb
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The phase of MySQLDB
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: The reason for the current phase of this MySQLDB
      jsonPath: .status.reason
      name: Reason
      type: string
    - description: schema_migration table if schema migration is enabled.
      jsonPath: .status.schemaMigration
      name: SchemaMigration
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MySQLDB is the Schema for the mysqldbs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: MySQLDBSpec defines the desired state of MySQLDB
            properties:
              dbName:
                description: MySQL Database name
                type: string
              mysqlName:
                description: MySQL (CRD) name to reference to, which decides the destination
                  MySQL server
                type: string
              schemaMigrationFromGitHub:
                description: MySQL Database Schema Migrations from GitHub
                properties:
                  owner:
                    type: string
                  path:
                    type: string
                  ref:
                    type: string
                  repo:
                    type: string
                required:
                - owner
                - path
                - repo
                type: object
            required:
            - dbName
            - mysqlName
            type: object
          status:
            description: MySQLDBStatus defines the observed state of MySQLDB
            properties:
              phase:
                description: The phase of database creation
                type: string
              reason:
                description: The reason for the current phase
                type: string
              schemaMigration:
                description: Schema Migration status
                properties:
                  dirty:
                    type: boolean
                  version:
                    type: integer
                required:
                - dirty
                - version
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
